version: "3.7"

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "3567:3567"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    command: mongod --auth
    networks:
      - spring

networks:
  spring:

volumes:
  mongo-data:

#  post-service:
#    build:
#      context: ./post-service
#    ports:
#      - "3568:8080"
#  friendship-service:
#    build:
#      context: ./friendship-service
#    ports:
#      - "3569:8080"
